name: sgp
channels:
  - pytorch
  - pyg
  - defaults
  - conda-forge
dependencies:
  - pip
  - pyg=2.0
  - python=3.8
  - pytorch=1.9
  - torchvision
  - torchaudio
  - wheel
  - pip:
      - einops
      - numpy
      - pandas
      - pytorch-lightning=1.5
      - scikit-learn
      - scipy
      - tables
      - test-tube
      - torchmetrics=0.7
      - tqdm
