#### Dataset params ###########################################################
window: 36
horizon: 22
horizon_lag: 7

dataset_name: pv
adj_knn: 100

#### Training params ##########################################################
batch_size: 2
batch_inference: 12

epochs: 230
batches_epoch: 32
scale_target: False

lr: 0.001
use_lr_schedule: False

#### Model params #############################################################
hidden_size: 64
ff_size: 128
kernel_size: 2
n_layers: 1
dropout: 0
