#### Windowing params #########################################################
window: 12
horizon: 12

#### Splitting params #########################################################
val_len: 0.1
test_len: 0.2

#### Training params ##########################################################
epochs: 300
patience: 50
batch_size: 64

lr: 0.01
use_lr_schedule: True
lr_gamma: 0.1
lr_milestones: [ 20, 30, 40 ]

#### Model params #############################################################
hidden_size: 64
ff_size: 128
kernel_size: 2
n_layers: 1
dropout: 0
