#### Windowing params #########################################################
window: 12
horizon: 12

#### Splitting params #########################################################
val_len: 0.1
test_len: 0.2

#### Training params ##########################################################
batch_size: 16
epochs: 300
patience: 50

lr: 0.0002
use_lr_schedule: True
lr_milestones: [ 50 ]
lr_gamma: 0.1

#### Model params #############################################################
hidden_size: 64
enc_layers: 2
gnn_layers: 2
full_graph: False  # True for FC
activation: 'silu'
