#### Windowing params #########################################################
window: 12
horizon: 12

#### Splitting params #########################################################
val_len: 0.1
test_len: 0.2

#### Training params ##########################################################
batch_size: 64
l2_reg: 0.0001
epochs: 300
patience: 50

lr: 0.001
use_lr_schedule: False

#### Model params #############################################################
hidden_size: 32
ff_size: 256
n_layers: 8
dropout: 0.3
temporal_kernel_size: 2
spatial_kernel_size: 2
dilation: 2
dilation_mod: 2
norm: batch
learned_adjacency: True
