#### Dataset params ###########################################################
window: 36
horizon: 22
horizon_lag: 7

dataset_name: cer
adj_knn: 500

#### Training params ##########################################################
batch_size: 1
batch_inference: 12
max_edges: 2200000
cut_edges_uniformly: True

epochs: 128
batches_epoch: 32

lr: 0.001
use_lr_schedule: False

#### Model params #############################################################
hidden_size: 64
ff_size: 128
kernel_size: 2
n_layers: 1
dropout: 0
